### ISSUE TITLE
Run the GenerateProjectFiles script in the Engine root.

### ISSUE THREAD

**Issue by ghost** [getsetgames/Chartboost#2]
How to `Run the GenerateProjectFiles script in the Engine root.` on Mac.

Could you please show whole command?

Thanks,

**Comment by ghost** [comment]
## test with unreal 4.16.1 version

0. put repo into [project]/Plugins/Chartboost.

1.
![image](https://user-images.githubusercontent.com/5056328/27258273-5b93620c-5429-11e7-9e70-98259f8585ed.png)

2. choose `no`
```
Plugin 'HTTPChunkInstaller' failed to load because module 'HTTPChunkInstaller' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.
```

**Comment by tatsujb** [comment]
why is this closed? this stupid error `Plugin 'HTTPChunkInstaller' failed to load because module 'HTTPChunkInstaller' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.` is obnoxious.
